# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Automated Tests

on:
    push:
        branches: [master]
    pull_request:
        branches: [master, develop]

permissions:
    contents: read

jobs:
    run-lint:
        runs-on: ubuntu-latest
        timeout-minutes: 30
        steps:
            - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
            - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
            - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
            - name: Check out repository code
              uses: actions/checkout@v4
            - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
            - run: echo "🖥️ The workflow is now ready to test your code on the runner."
            - name: Use Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 22
                  cache: "npm"
            - name: Install dependencies and run tests
              run: |
                  npm ci
                  npm run lint
            - run: echo "🍏 This job's status is ${{ job.status }}."
